x-pipeline-common: &pipeline-common
  build: .
  image: newsnack-pipeline:latest
  env_file: .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
  user: "${AIRFLOW_UID:-50000}:0"
  restart: always

services:
  pipeline-webserver:
    <<: *pipeline-common
    command: webserver
    ports:
      - "8081:8080"

  pipeline-scheduler:
    <<: *pipeline-common
    command: scheduler
